'use client';
import { useEffect, useState } from 'react';
import { Users, CreditCard, ShieldCheck, BookOpen, Layers, Settings } from 'lucide-react';
import { Empty, date, money } from '../../components/Common';
import { api } from '../api';
export default function Overview({ navigate }: { navigate: (tab: string) => void }) {
 const [data,setData]=useState<any>(null); const [error,setError]=useState('');
 useEffect(()=>{Promise.all([api('payments/admin'),api('admin/students'),api('access/list'),api('questions/admin')]).then(([payments,students,access,questions])=>setData({payments,students,access,questions})).catch(e=>setError(e.message));},[]);
 if(error)return <div className="notice error">{error}</div>;
 if(!data)return <p>Loading platform overview…</p>;
 const pending=data.payments.filter((p:any)=>p.status==='pending');
 const active=data.access.filter((s:any)=>s.status==='active'&&s.starts<=Date.now()&&s.expires>Date.now()).length;
 const published=data.questions.filter((q:any)=>q.status==='published').length;
 const stats=[['Students',data.students.filter((s:any)=>s.role==='student').length,'Registered student accounts',Users],['Pending payments',pending.length,'Waiting for your review',CreditCard],['Active subscriptions',active,'Current approved access',ShieldCheck],['Published BCQs',published,'Available in the question bank',BookOpen]];
 return <><section className="welcome-card"><div><span className="eyebrow">PLATFORM OVERVIEW</span><h2>Manage your platform.</h2><p>{pending.length?`${pending.length} payment submission${pending.length===1?'':'s'} waiting for review.`:'Your student accounts, payments and academic content in one place.'}</p></div><button className="btn" onClick={()=>navigate('payments')}>Review payments</button></section><div className="stats">{stats.map(([label,value,detail,Icon]:any)=><div className="stat" key={label}><div className="stat-top">{label}<Icon/></div><strong>{value}</strong><small>{detail}</small></div>)}</div><div className="grid-two"><div><section className="panel"><div className="panel-head"><h3>Manage your platform</h3><span className="badge-count">ADMINISTRATION</span></div><div className="quick-grid">{[['students','Manage students','Review enrollment and account details.',Users],['access','Manage access','Review subscriptions and access dates.',ShieldCheck],['questions','Question bank','Create, import and publish BCQs.',BookOpen],['packages','Packages & pricing','Configure access packages.',Settings]].map(([tab,label,description,Icon]:any)=><button className="quick" key={tab} onClick={()=>navigate(tab)}><Icon/><span><strong>{label}</strong><small>{description}</small></span></button>)}</div></section><section className="panel"><div className="panel-head"><h3>Pending payment reviews</h3><button className="text-button" onClick={()=>navigate('payments')}>View payments</button></div>{pending.length?pending.slice(0,5).map((p:any)=><div className="list-row" key={p.id}><span><strong>{p.name || 'Student'}</strong><small>{p.method} · {money(p.amount)} · {date(p.created)}</small></span><button className="btn" onClick={()=>navigate('payments')}>Review</button></div>):<Empty title="No pending payments" text="New payment submissions will appear here."/>}</section></div><div><section className="panel"><div className="panel-head"><h3>Question bank</h3><BookOpen size={20}/></div><div className="info-line"><span>Published</span><span>{published}</span></div><div className="info-line"><span>Drafts</span><span>{data.questions.filter((q:any)=>q.status==='draft').length}</span></div><div className="info-line"><span>Archived</span><span>{data.questions.filter((q:any)=>q.status==='archived').length}</span></div><button className="text-button" onClick={()=>navigate('questions')}>Manage question bank</button></section><section className="panel"><div className="panel-head"><h3>Platform settings</h3><Layers size={20}/></div>{[['categories','Academic categories'],['accounts','Payment accounts'],['branding','Branding'],['audit','Audit history']].map(([tab,label])=><div key={tab}><button className="text-button" onClick={()=>navigate(tab)}>{label}</button></div>)}</section></div></div></>;
}
